import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const playgroundDir = resolve(fileURLToPath(new URL("..", import.meta.url)));
const workerSourcePath = resolve(playgroundDir, "../browser/src/worker.ts");
const workerSourceDir = dirname(workerSourcePath);
const workerOutputPath = resolve(playgroundDir, "secure-exec-worker.js");
const appSourcePath = resolve(playgroundDir, "frontend/app.ts");
const appOutputPath = resolve(playgroundDir, "dist/app.js");

const BRIDGE_IMPORT_BLOCK = `\tlet bridgeModule: Record<string, unknown>;
\ttry {
\t\tbridgeModule = await dynamicImportModule("@secure-exec/nodejs/internal/bridge");
\t} catch {
\t\t// Vite browser tests may need a second attempt during source execution.
\t\ttry {
\t\t\tbridgeModule = await dynamicImportModule("@secure-exec/nodejs/internal/bridge");
\t\t} catch {
\t\t\tthrow new Error("Failed to load bridge module from @secure-exec/nodejs");
\t\t}
\t}`;

async function writeGeneratedBundle(outputPath: string, sourcePath: string): Promise<void> {
	const outputSource = await readFile(outputPath, "utf8");
	await writeFile(outputPath, `// Generated by ${sourcePath}\n${outputSource}`);
}

async function buildWorkerBundle(): Promise<void> {
	const originalSource = await readFile(workerSourcePath, "utf8");
	const patchedSource = originalSource
		.replace(
			'import { mkdir } from "../fs-helpers.js";',
			'import { mkdir } from "../fs-helpers.js";\nimport * as browserWorkerBridgeModule from "@secure-exec/nodejs/internal/bridge";',
		)
		.replace(BRIDGE_IMPORT_BLOCK, "\tconst bridgeModule = browserWorkerBridgeModule;");

	await build({
		bundle: true,
		external: [
			"fs",
			"module",
			"path",
			"util",
			"node:fs",
			"node:fs/promises",
			"node:module",
			"node:path",
			"node:util",
		],
		format: "esm",
		legalComments: "none",
		minify: true,
		outfile: workerOutputPath,
		platform: "browser",
		stdin: {
			contents: patchedSource,
			loader: "ts",
			resolveDir: workerSourceDir,
			sourcefile: workerSourcePath,
		},
		target: "es2022",
	});

	await writeGeneratedBundle(workerOutputPath, "packages/playground/scripts/build-worker.ts");
}

async function buildAppBundle(): Promise<void> {
	await build({
		bundle: false,
		entryPoints: [appSourcePath],
		format: "esm",
		legalComments: "none",
		outfile: appOutputPath,
		platform: "browser",
		target: "es2022",
	});

	await writeGeneratedBundle(appOutputPath, "packages/playground/scripts/build-worker.ts");
}

async function main(): Promise<void> {
	await Promise.all([buildWorkerBundle(), buildAppBundle()]);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
